services: 
    flask-db: 
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: ediJM26
        MYSQL_DATABASE: urls
      ports: 
        - 33069:33060


    web-flask: 
        build: .
        restart: always
        command: python main.py
        ports:
            - 5000:5000
        depends_on:
            - flask-db